'use client';

import { useEffect, useRef, useState } from 'react';
import * as THREE from 'three';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';
import { ColladaLoader } from 'three/examples/jsm/loaders/ColladaLoader.js';
import { TransformControls } from 'three/examples/jsm/controls/TransformControls.js';

const limits = [179.9, 179.9, 270, 190, 179.9, 225];
const axes = [new THREE.Vector3(0,0,1),new THREE.Vector3(0,1,0),new THREE.Vector3(0,-1,0),new THREE.Vector3(-1,0,0),new THREE.Vector3(0,-1,0),new THREE.Vector3(-1,0,0)];
const origins = [[0,0,.245],[0,0,0],[0,0,.71],[0,0,0],[.54,0,0],[0,-.15,0]] as const;
const meshOffsets = [[0,0,-.245],[0,0,-.245],[0,0,-.955],[0,0,-.955],[-.54,0,-.955],[-.54,.15,-.955]] as const;

function solveIK(groups:THREE.Group[],flange:THREE.Group,target:THREE.Object3D,start:number[],mode:'translate'|'rotate'){
  const angles=start.map(THREE.MathUtils.degToRad); const eps=.001; const p=new THREE.Vector3(); const q=new THREE.Quaternion(); const tp=new THREE.Vector3(); const tq=new THREE.Quaternion(); target.getWorldPosition(tp); target.getWorldQuaternion(tq);
  const apply=()=>groups.forEach((g,i)=>g.quaternion.setFromAxisAngle(axes[i],angles[i]));
  const rotationError=(from:THREE.Quaternion,to:THREE.Quaternion)=>{const d=to.clone().multiply(from.clone().invert());if(d.w<0)d.set(-d.x,-d.y,-d.z,-d.w);return new THREE.Vector3(d.x,d.y,d.z).multiplyScalar(2)};
  if(mode==='translate'){
    for(let pass=0;pass<36;pass++){
      apply();flange.updateWorldMatrix(true,false);flange.getWorldPosition(p);if(p.distanceTo(tp)<.0015)break;
      for(let i=5;i>=0;i--){apply();flange.updateWorldMatrix(true,false);const jointPos=new THREE.Vector3();const endPos=new THREE.Vector3();groups[i].getWorldPosition(jointPos);flange.getWorldPosition(endPos);const parentQ=new THREE.Quaternion();groups[i].parent?.getWorldQuaternion(parentQ);const axisWorld=axes[i].clone().applyQuaternion(parentQ).normalize();const toEnd=endPos.sub(jointPos);const toTarget=tp.clone().sub(jointPos);toEnd.addScaledVector(axisWorld,-toEnd.dot(axisWorld));toTarget.addScaledVector(axisWorld,-toTarget.dot(axisWorld));if(toEnd.lengthSq()<1e-8||toTarget.lengthSq()<1e-8)continue;toEnd.normalize();toTarget.normalize();const angle=Math.atan2(axisWorld.dot(toEnd.clone().cross(toTarget)),THREE.MathUtils.clamp(toEnd.dot(toTarget),-1,1));angles[i]=THREE.MathUtils.clamp(angles[i]+THREE.MathUtils.clamp(angle,-.35,.35),THREE.MathUtils.degToRad(-limits[i]),THREE.MathUtils.degToRad(limits[i]));}
    }
    apply();return angles.map(THREE.MathUtils.radToDeg);
  }
  for(let pass=0;pass<18;pass++){
    apply();flange.updateWorldMatrix(true,false);flange.getWorldPosition(p);flange.getWorldQuaternion(q);if(p.distanceTo(tp)<.002&&rotationError(q,tq).length()<.018)break;
    for(let i=5;i>=0;i--){apply();flange.updateWorldMatrix(true,false);const p0=new THREE.Vector3();const q0=new THREE.Quaternion();flange.getWorldPosition(p0);flange.getWorldQuaternion(q0);const pe=tp.clone().sub(p0);const re=rotationError(q0,tq);angles[i]+=eps;apply();flange.updateWorldMatrix(true,false);const p1=new THREE.Vector3();const q1=new THREE.Quaternion();flange.getWorldPosition(p1);flange.getWorldQuaternion(q1);angles[i]-=eps;const dp=p1.sub(p0).divideScalar(eps);const dr=rotationError(q0,q1).divideScalar(eps);const weight=.65;const delta=THREE.MathUtils.clamp((dp.dot(pe)+weight*dr.dot(re))/(dp.lengthSq()+weight*dr.lengthSq()+1e-5)*.72,-.18,.18);angles[i]=THREE.MathUtils.clamp(angles[i]+delta,THREE.MathUtils.degToRad(-limits[i]),THREE.MathUtils.degToRad(limits[i]));}
  }
  apply(); return angles.map(THREE.MathUtils.radToDeg);
}

function RobotViewport({ joints, basePosition, onBaseMove, ikMode, onJointsChange, baseMoveMode, baseHandMode }: { joints: number[]; basePosition: [number, number, number]; onBaseMove: (position: [number, number, number]) => void; ikMode:'translate'|'rotate'; onJointsChange:(joints:number[])=>void; baseMoveMode:boolean; baseHandMode:'follow'|'fixed' }) {
  const mountRef = useRef<HTMLDivElement>(null);
  const groupsRef = useRef<THREE.Group[]>([]);
  const robotRef = useRef<THREE.Group | null>(null);
  const targetRef = useRef<THREE.Mesh | null>(null);
  const flangeRef = useRef<THREE.Group | null>(null);
  const jointsRef = useRef(joints); jointsRef.current = joints;
  const baseRef = useRef(basePosition); baseRef.current = basePosition;
  const moveRef = useRef(onBaseMove); moveRef.current = onBaseMove;
  const jointsChangeRef=useRef(onJointsChange);jointsChangeRef.current=onJointsChange;
  const transformRef=useRef<TransformControls|null>(null);
  const baseMoveRef=useRef(baseMoveMode);baseMoveRef.current=baseMoveMode;
  const baseHandRef=useRef(baseHandMode);baseHandRef.current=baseHandMode;
  useEffect(() => {
    const mount = mountRef.current; if (!mount) return;
    const scene = new THREE.Scene(); scene.background = new THREE.Color('#101823'); scene.fog = new THREE.Fog('#101823',5,11);
    const camera = new THREE.PerspectiveCamera(36,1,.01,30); camera.position.set(2.7,-3.5,2.35);
    const renderer = new THREE.WebGLRenderer({antialias:true}); renderer.setPixelRatio(Math.min(devicePixelRatio,2)); renderer.outputColorSpace=THREE.SRGBColorSpace; renderer.shadowMap.enabled=true; mount.appendChild(renderer.domElement);
    const controls = new OrbitControls(camera,renderer.domElement); controls.target.set(.15,0,.75); controls.enableDamping=true; controls.minDistance=1.4; controls.maxDistance=8;
    scene.add(new THREE.HemisphereLight('#d9efff','#26313a',2.1)); const key=new THREE.DirectionalLight('#fff7dc',5.2); key.position.set(-2,-3,5); key.castShadow=true; scene.add(key);
    const floor=new THREE.Mesh(new THREE.CircleGeometry(4.5,96),new THREE.MeshStandardMaterial({color:'#19232d',roughness:.82,metalness:.08})); floor.rotation.x=-Math.PI/2; floor.receiveShadow=true; scene.add(floor);
    const grid=new THREE.GridHelper(9,36,'#415361','#263542'); grid.material.opacity=.48; grid.material.transparent=true; scene.add(grid);
    const robotRoot=new THREE.Group(); robotRef.current=robotRoot; robotRoot.rotation.x=-Math.PI/2; robotRoot.position.set(baseRef.current[0],baseRef.current[2],baseRef.current[1]); scene.add(robotRoot); const loader=new ColladaLoader();
    const work=new THREE.Mesh(new THREE.CylinderGeometry(.015,.015,.3,32),new THREE.MeshStandardMaterial({color:'#ffd400',metalness:.55,roughness:.28})); work.rotation.x=Math.PI/2; work.position.set(0,1.12,0); work.castShadow=true; scene.add(work);
    const workRing=new THREE.Mesh(new THREE.RingGeometry(.035,.043,48),new THREE.MeshBasicMaterial({color:'#ffd400',side:THREE.DoubleSide,transparent:true,opacity:.75})); workRing.rotation.x=-Math.PI/2; workRing.position.set(0,.002,0); scene.add(workRing);
    const measureGeometry=new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(0,.006,0),new THREE.Vector3(0,1.12,0)]); const measure=new THREE.Line(measureGeometry,new THREE.LineDashedMaterial({color:'#9fb0bb',dashSize:.045,gapSize:.025})); measure.computeLineDistances(); scene.add(measure);
    const assetBasePath=process.env.NEXT_PUBLIC_BASE_PATH??'';
    const loadMesh=async(name:string)=>{const result=await loader.loadAsync(`${assetBasePath}/models/crx20ia_l/${name}.dae`); result.scene.rotation.set(0,0,0); result.scene.updateMatrix(); result.scene.traverse((o)=>{if(o instanceof THREE.Mesh){o.castShadow=true;o.receiveShadow=true;const ms=Array.isArray(o.material)?o.material:[o.material];ms.forEach(m=>m.side=THREE.DoubleSide)}});return result.scene};
    let transform:TransformControls|null=null;let helper:THREE.Object3D|null=null;let ikTarget:THREE.Mesh|null=null;let flangeNode:THREE.Group|null=null;let disposed=false; Promise.all(['base','j1','j2','j3','j4','j5','j6'].map(loadMesh)).then(meshes=>{if(disposed)return;robotRoot.add(meshes[0]);let parent=robotRoot;groupsRef.current=[];for(let i=0;i<6;i++){const group=new THREE.Group();group.position.set(...origins[i]);meshes[i+1].position.set(...meshOffsets[i]);group.add(meshes[i+1]);parent.add(group);parent=group;groupsRef.current.push(group);group.quaternion.setFromAxisAngle(axes[i],THREE.MathUtils.degToRad(jointsRef.current[i]))}const flange=new THREE.Group();flangeNode=flange;flangeRef.current=flange;flange.position.set(.16,0,0);parent.add(flange);flange.updateWorldMatrix(true,false);const target=new THREE.Mesh(new THREE.SphereGeometry(.05,24,16),new THREE.MeshStandardMaterial({color:'#ff3b30',emissive:'#64110d',metalness:.25,roughness:.35}));ikTarget=target;targetRef.current=target;flange.getWorldPosition(target.position);flange.getWorldQuaternion(target.quaternion);scene.add(target);transform=new TransformControls(camera,renderer.domElement);transform.setMode(ikMode);transform.setSize(.75);transform.attach(target);helper=transform.getHelper();scene.add(helper);transformRef.current=transform;transform.addEventListener('dragging-changed',(event:any)=>{controls.enabled=!event.value});transform.addEventListener('objectChange',()=>{const mode=transform?.getMode()??'translate';const next=solveIK(groupsRef.current,flange,target,jointsRef.current,mode);jointsRef.current=next;jointsChangeRef.current(next)})});
    const raycaster=new THREE.Raycaster(); const pointer=new THREE.Vector2(); const floorPlane=new THREE.Plane(new THREE.Vector3(0,1,0),0); const handPlane=new THREE.Plane(); const hitPoint=new THREE.Vector3(); const dragOffset=new THREE.Vector3(); let dragging=false; let handDragging=false; let verticalDrag=false; let dragStartY=0; let dragStartHeight=0;
    const pointRay=(event:PointerEvent)=>{const rect=renderer.domElement.getBoundingClientRect();pointer.x=((event.clientX-rect.left)/rect.width)*2-1;pointer.y=-((event.clientY-rect.top)/rect.height)*2+1;raycaster.setFromCamera(pointer,camera)};
    const pointerDown=(event:PointerEvent)=>{pointRay(event);if(!baseMoveRef.current&&ikTarget&&raycaster.intersectObject(ikTarget,true).length>0){handDragging=true;handPlane.setFromNormalAndCoplanarPoint(camera.getWorldDirection(new THREE.Vector3()),ikTarget.position);controls.enabled=false;renderer.domElement.setPointerCapture(event.pointerId);renderer.domElement.style.cursor='move';return}if(!baseMoveRef.current&&helper&&raycaster.intersectObject(helper,true).length>0)return;if(raycaster.intersectObject(robotRoot,true).length===0)return;if(raycaster.ray.intersectPlane(floorPlane,hitPoint)){dragging=true;verticalDrag=event.shiftKey;dragStartY=event.clientY;dragStartHeight=robotRoot.position.y;dragOffset.set(robotRoot.position.x-hitPoint.x,0,robotRoot.position.z-hitPoint.z);controls.enabled=false;renderer.domElement.setPointerCapture(event.pointerId);renderer.domElement.style.cursor=verticalDrag?'ns-resize':'grabbing'}};
    const updateBase=(x:number,z:number,height:number)=>{const delta=new THREE.Vector3(x-robotRoot.position.x,height-robotRoot.position.y,z-robotRoot.position.z);robotRoot.position.set(x,height,z);robotRoot.updateWorldMatrix(true,true);if(ikTarget&&flangeNode){if(baseHandRef.current==='follow'){ikTarget.position.add(delta)}else{const next=solveIK(groupsRef.current,flangeNode,ikTarget,jointsRef.current,'rotate');jointsRef.current=next;jointsChangeRef.current(next)}}moveRef.current([x,z,height])};
    const pointerMove=(event:PointerEvent)=>{if(handDragging&&ikTarget&&flangeNode){pointRay(event);if(raycaster.ray.intersectPlane(handPlane,hitPoint)){ikTarget.position.copy(hitPoint);const next=solveIK(groupsRef.current,flangeNode,ikTarget,jointsRef.current,'translate');jointsRef.current=next;jointsChangeRef.current(next)}return}if(!dragging)return;if(verticalDrag){const height=THREE.MathUtils.clamp(dragStartHeight+(dragStartY-event.clientY)*.005,-2,2);updateBase(robotRoot.position.x,robotRoot.position.z,height);return}pointRay(event);if(raycaster.ray.intersectPlane(floorPlane,hitPoint)){const x=THREE.MathUtils.clamp(hitPoint.x+dragOffset.x,-2,2);const z=THREE.MathUtils.clamp(hitPoint.z+dragOffset.z,-2,2);updateBase(x,z,robotRoot.position.y)}};
    const pointerUp=(event:PointerEvent)=>{if(!dragging&&!handDragging)return;dragging=false;handDragging=false;controls.enabled=true;renderer.domElement.releasePointerCapture(event.pointerId);renderer.domElement.style.cursor='grab'};
    renderer.domElement.style.cursor='grab'; renderer.domElement.addEventListener('pointerdown',pointerDown); renderer.domElement.addEventListener('pointermove',pointerMove); renderer.domElement.addEventListener('pointerup',pointerUp); renderer.domElement.addEventListener('pointercancel',pointerUp);
    const resize=()=>{renderer.setSize(mount.clientWidth,mount.clientHeight,false);camera.aspect=mount.clientWidth/Math.max(mount.clientHeight,1);camera.updateProjectionMatrix()};const observer=new ResizeObserver(resize);observer.observe(mount);let frame=0;const animate=()=>{frame=requestAnimationFrame(animate);controls.update();renderer.render(scene,camera)};resize();animate();
    return()=>{disposed=true;robotRef.current=null;targetRef.current=null;flangeRef.current=null;transformRef.current=null;if(transform){transform.detach();transform.dispose()}if(helper)scene.remove(helper);cancelAnimationFrame(frame);observer.disconnect();controls.dispose();renderer.domElement.removeEventListener('pointerdown',pointerDown);renderer.domElement.removeEventListener('pointermove',pointerMove);renderer.domElement.removeEventListener('pointerup',pointerUp);renderer.domElement.removeEventListener('pointercancel',pointerUp);renderer.dispose();mount.removeChild(renderer.domElement)};
  },[]);
  useEffect(()=>{groupsRef.current.forEach((g,i)=>g.quaternion.setFromAxisAngle(axes[i],THREE.MathUtils.degToRad(joints[i])))},[joints]);
  useEffect(()=>{const robot=robotRef.current;if(!robot)return;const next=new THREE.Vector3(basePosition[0],basePosition[2],basePosition[1]);const delta=next.clone().sub(robot.position);if(delta.lengthSq()<1e-12)return;robot.position.copy(next);robot.updateWorldMatrix(true,true);const target=targetRef.current;const flange=flangeRef.current;if(target&&flange){if(baseHandRef.current==='follow')target.position.add(delta);else{const solved=solveIK(groupsRef.current,flange,target,jointsRef.current,'rotate');jointsRef.current=solved;jointsChangeRef.current(solved)}}},[basePosition]);
  useEffect(()=>{transformRef.current?.setMode(ikMode)},[ikMode]);
  useEffect(()=>{const helper=transformRef.current?.getHelper();if(helper)helper.visible=!baseMoveMode},[baseMoveMode]);
  return <div ref={mountRef} className="viewport" aria-label="CRX-20iA/L 3D viewport"/>;
}

export default function Home(){
  const [joints,setJoints]=useState([0,-25,55,0,60,0]); const [playing,setPlaying]=useState(false);
  const [basePosition,setBasePosition]=useState<[number,number,number]>([0,0,0]);
  const [ikMode,setIkMode]=useState<'translate'|'rotate'>('translate');
  const [baseMoveMode,setBaseMoveMode]=useState(false);
  const [baseHandMode,setBaseHandMode]=useState<'follow'|'fixed'>('follow');
  const signed=(value:number)=>`${value>=0?'+':''}${Math.round(value)}`;
  useEffect(()=>{if(!playing)return;const start=performance.now();const timer=setInterval(()=>{const t=(performance.now()-start)/1000;setJoints([Math.sin(t*.42)*80,-30+Math.sin(t*.55)*35,45+Math.sin(t*.62)*55,Math.sin(t*.8)*90,55+Math.sin(t*.7)*30,Math.sin(t)*135])},30);return()=>clearInterval(timer)},[playing]);
  const changeJoint=(index:number,value:number)=>{setPlaying(false);setJoints(c=>c.map((v,i)=>i===index?value:v))};
  return <main>
    <header className="topbar"><div className="brand"><span className="brand-mark">F</span><div><strong>CRX LAB</strong><small>ROBOT VISUALIZER</small></div></div><div className="model"><span className="status-dot"/><b>CRX-20iA/L</b><span>OFFLINE MODEL</span></div><a href="https://github.com/FANUC-CORPORATION/fanuc_description" target="_blank" rel="noreferrer">FANUC公式データ ↗</a></header>
    <section className="workspace"><div className="stage"><RobotViewport joints={joints} basePosition={basePosition} onBaseMove={setBasePosition} ikMode={ikMode} onJointsChange={setJoints} baseMoveMode={baseMoveMode} baseHandMode={baseHandMode}/><div className="stage-title"><span>LAYOUT SIMULATION</span><strong>CRX-20iA/L × WORK</strong><div className="coordinates">WORK → ROBOT　X {signed(basePosition[0]*1000)}　Y {signed(basePosition[1]*1000)}　Z {signed(basePosition[2]*1000-1120)} mm</div></div><div className="work-label"><b>WORK — HORIZONTAL</b><span>Ø30 × 300 mm</span><small>CENTER Z +1,120 mm</small></div><div className="hint">{baseMoveMode?`本体ドラッグ：床面移動　Shift＋ドラッグ：上下移動　［ハンド${baseHandMode==='fixed'?'固定':'追従'}］`:'赤い先端ターゲットをドラッグ：逆運動学'}</div><div className="axis"><i className="x">X</i><i className="y">Y</i><i className="z">Z</i></div></div>
      <aside className="panel"><div className="mode-switch"><button className={!baseMoveMode?'active':''} onClick={()=>setBaseMoveMode(false)}>ハンド操作</button><button className={baseMoveMode?'active':''} onClick={()=>setBaseMoveMode(true)}>ロボット設置</button></div><div className="ik-control"><small>END EFFECTOR / INVERSE KINEMATICS</small><h2>ハンド先端操作</h2><div><button className={ikMode==='translate'?'selected':''} onClick={()=>{setBaseMoveMode(false);setIkMode('translate')}}>↔ 位置移動</button><button className={ikMode==='rotate'?'selected':''} onClick={()=>{setBaseMoveMode(false);setIkMode('rotate')}}>⟳ 向き回転</button></div><p>赤いターゲットの軸をドラッグすると、J1〜J6が自動追従します。</p></div><div className="relative"><small>WORK → ROBOT MOUNT CENTER</small><h2>ワーク基準の取付座標</h2><div><span>X<b>{signed(basePosition[0]*1000)} mm</b></span><span>Y<b>{signed(basePosition[1]*1000)} mm</b></span><span>Z<b>{signed(basePosition[2]*1000-1120)} mm</b></span></div></div><div className="placement"><small>ABSOLUTE BASE PLACEMENT</small><h2>床面基準の設置位置</h2><div className="hand-lock"><button className={baseHandMode==='follow'?'active':''} onClick={()=>{setBaseMoveMode(true);setBaseHandMode('follow')}}>◎ ハンド追従</button><button className={baseHandMode==='fixed'?'active':''} onClick={()=>{setBaseMoveMode(true);setBaseHandMode('fixed')}}>⊙ ハンド固定</button></div><p className="placement-note">{baseHandMode==='fixed'?'先端位置・向きを維持してJ1〜J6を自動補正':'先端中心点をロボットと一緒に移動'}</p><div><span>X <b>{Math.round(basePosition[0]*1000)} mm</b></span><span>Y <b>{Math.round(basePosition[1]*1000)} mm</b></span><span>Z <b>{Math.round(basePosition[2]*1000)} mm</b></span></div><label className="height-control">−2000<input aria-label="Robot height" type="range" min="-2000" max="2000" step="5" value={Math.round(basePosition[2]*1000)} onChange={e=>setBasePosition([basePosition[0],basePosition[1],Number(e.target.value)/1000])}/>＋2000</label><button onClick={()=>setBasePosition([0,0,0])}>原点へ戻す</button></div><div className="panel-heading"><div><small>JOINT CONTROL</small><h1>関節角度</h1></div><button onClick={()=>{setPlaying(false);setJoints([0,-25,55,0,60,0])}}>RESET</button></div><div className="joint-list">{joints.map((value,i)=><label className="joint" key={i}><div><b>J{i+1}</b><span>{value.toFixed(1)}°</span></div><input aria-label={`J${i+1} joint angle`} type="range" min={-limits[i]} max={limits[i]} step="0.1" value={value} onChange={e=>changeJoint(i,Number(e.target.value))}/><small>−{limits[i]}° <em/> +{limits[i]}°</small></label>)}</div>
        <button className={`play ${playing?'active':''}`} onClick={()=>setPlaying(v=>!v)}><span>{playing?'Ⅱ':'▶'}</span>{playing?'モーション停止':'デモモーション再生'}</button><div className="specs"><span><small>軸数</small><b>6 AXIS</b></span><span><small>可搬質量</small><b>20 kg</b></span><span><small>リーチ</small><b>1,418 mm</b></span></div><p className="source">MODEL SOURCE<br/><b>FANUC-CORPORATION / fanuc_description</b></p>
      </aside></section>
  </main>
}
